### PR TITLE
Hhw wgg dev

### PR DESCRIPTION
**Pull request by chuwang1**
1.updated FL selection
2.Add lepton SF into FL channel
3.Modified photon systematics
4.Add one option into HHWWgg_Run_Jobs.sh to recalculate Pdf weight

### CODE REVIEW

**Comment by atishelmanch** [comment]
Hey @chuwang1 - I've added some SF implementation so there are some conflicts now. Can you please update this pull request by committing to the chuwang1:HHWWgg_dev branch (there shouldn't be a need for a new pull request) with the final selections you would like for HHWWggTag_3 of the analysis? You can include the scale factors yourself, or I can do this, no problem on my end.

**Comment by chuwang1** [comment]
I have fixed them.

**Review by atishelmanch — CHANGES_REQUESTED** [review]
Thanks Chu. Here are my comments: 

- I think be default, classes_def.xml should be included in the gitignore. When someone updates their repo, they will then just need to rebuild the classes_def file. I think it's less ideal if a file with a newer classversion is pushed to a user's repository. I propose this file be removed from the PR
- What's the purpose of "unbinnedSystematics in workspaceStd? Probably related: What's the purpose of this change in association with the CategoryDumper.h update you've added?
- Looking at your jsons, we probably want to also have "HHWWgguseZeroVtx=1" added [1], unless we do a check showing the Hgg vtx is better for Fully Leptonic. The zeroeth is probably the best first guess since we expect two high pT leptons in the FL process vtx, although it would be interesting to check since there are also two neutrinos + photons from Hgg.

[1] https://github.com/chuwang1/flashgg/commit/9e1ca76a9d806df273a577dd94d39b9cae6694c5#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R94

**Comment by atishelmanch** [comment]
To save time, I'm just going to merge this now because the comments above are small.

**Comment by chuwang1** [comment]
> Thanks Chu. Here are my comments:
> 
> * I think be default, classes_def.xml should be included in the gitignore. When someone updates their repo, they will then just need to rebuild the classes_def file. I think it's less ideal if a file with a newer classversion is pushed to a user's repository. I propose this file be removed from the PR
> * What's the purpose of "unbinnedSystematics in workspaceStd? Probably related: What's the purpose of this change in association with the CategoryDumper.h update you've added?
> * Looking at your jsons, we probably want to also have "HHWWgguseZeroVtx=1" added [1], unless we do a check showing the Hgg vtx is better for Fully Leptonic. The zeroeth is probably the best first guess since we expect two high pT leptons in the FL process vtx, although it would be interesting to check since there are also two neutrinos + photons from Hgg.
> 
> [1] [chuwang1@9e1ca76#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R94](https://github.com/chuwang1/flashgg/commit/9e1ca76a9d806df273a577dd94d39b9cae6694c5#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R94)

Hi @atishelmanch 
For unbinnedSystematics issue, I think now it is ok, you have already changed the workspaceStd.py and CategoryDumper.h.
For HHWWgguseZeroVtx=1, 
yes, I want to add this option.

Thanks for your help to merge this.

**Pull request merged**
