### PR TITLE
Fully Hadronic different methods for jet selections

### PR DESCRIPTION
**Pull request by ram1123**
- Added 4 different method for jet selections
   1. Take 4 leading jets
   2. Select 2 jets using W-mass constraint then another two using Higgs mass constraints.
   3. Select 2 jets using W-mass and another 2 as leading jets from the remaining jets.
   4. Select 4 jets using Higgs mass constraint only.

Apart from this few another changes:

1. Private JSON files for FH channel that includes resonant and non-resonant samples.
2. QCD HT-binned JSON files
3. Updated cross-section in the cross-section json file.

Other changes:
1. Some of QCD files (official ones) fails the flashgg step because of MET input tag. In some of them the MET input tag is ** flashggMetsCorr** instead of ** flashggMets**. So, added the patch for this [flashggMets_To_flashggMetsCorr.patch](https://github.com/ram1123/flashgg/blob/af17113730a977568daa3cbd773f00d4fb81f88d/flashggMets_To_flashggMetsCorr.patch)

2. If we forget to add the cross-section in the cross-section json file then it gives strange error. So, to protect from this I added following in the [MetaData/python/samples_utils.py#L981-L984](https://github.com/ram1123/flashgg/blob/af17113730a977568daa3cbd773f00d4fb81f88d/MetaData/python/samples_utils.py#L981-L984)

   ```python
                if prim in self.cross_sections_:
                    xsec = self.cross_sections_[prim]
                else:
                    raise Exception("No cross-section info found for dataset : /%s" % ( prim))
   ```

3. Updated README.md
1.  Systematics Fix (Suggested by Chu)
    1.  Replaced **or** to **and** here: https://github.com/ram1123/flashgg/blob/5cecd765ce38c9eb548a1ca2df0ee9734ee9c270/Taggers/interface/CategoryDumper.h#L580
     1.  Added the option: https://github.com/ram1123/flashgg/blob/5cecd765ce38c9eb548a1ca2df0ee9734ee9c270/Systematics/test/workspaceStd.py#L756
1. Added string "GluGluToHH" in signal_process to identify the signal process: https://github.com/ram1123/flashgg/blob/5cecd765ce38c9eb548a1ca2df0ee9734ee9c270/Systematics/test/workspaceStd.py#L471
1. Set L1TriggerPrefire option to true in [MetaData/data/MetaConditions/Era2016_RR-17Jul2018_v1.json](https://github.com/ram1123/flashgg/blob/5cecd765ce38c9eb548a1ca2df0ee9734ee9c270/MetaData/data/MetaConditions/Era2016_RR-17Jul2018_v1.json)

Some other small changes.

### CODE REVIEW

**Comment by atishelmanch** [comment]
Hey @ram1123 - I've added some SF implementation so there are some conflicts now. Can you please update this pull request with the final selections you would like for HHWWggTag_2 of the analysis? You can include the scale factors yourself, or I can do this, no problem on my end.

**Comment by ram1123** [comment]
Hi @atishelmanch ,

Thanks for adding the SFs and improving the framework.

I will fix the merge conflict and include the scale factors for FH case.
I will ping you once I am done.

**Comment by ram1123** [comment]
Hi @atishelmanch ,

I fixed the conflicts in my branch.  

Chu also made the pull request so I will suggest to  merge his pull request then I have to fix the conflict again. Let me know once you merge Chu pull request. Then I will resolve the conflicts with FH and let you know.

**Comment by atishelmanch** [comment]
Hey @ram1123 - after merging Chu's pull request it looks like there are now some (minor) conflicts with your PR now. Could you resolve them? I don't think it should be difficult. And you can add the classes_def.xml file to the gitignore. Thank you.

**Comment by ram1123** [comment]
yes...Already fixed the conflicts. But, while running locally  and trying to fix the compilation issue.

Probably Chu forgot to define **sumpT** [here](https://github.com/chuwang1/flashgg/blob/9b3b1d21fe95040ed92cc798ba4e1e5217d5b763/Taggers/plugins/HHWWggTagProducer.cc#L1172)

He added this for both FH and FL. Will notify soon once I successfully test this.

**Comment by ram1123** [comment]
In my last commit I deleted the file `DataFormats/src/classes_def.xml` and added it into the `.gitignore`.

**Comment by atishelmanch** [comment]
👍

**Pull request merged**
